### ISSUE TITLE
File in shared folder

### ISSUE THREAD

**Issue by seertenedos** [r0ld3x/terabox-app#11]
Could you provide any guidance for generating direct download links for a particular file in a shared folder. I wrote a little app to monitor a shared folder for new files and then i want to auto download them but i am having issues generating the direct download links or understanding the steps to do so. None of the link generators i have seen can take a set of params to point to a file in a path in a share or use the fid etc of the file in the share. Happy to bounce though another site like yours if needed but would perfer to embed the logic if it is easy.

hoping since your link generator works for videos as the sharelink you may be able to guide or have insight on doing it for a file in a folder share.

**Comment by r0ld3x** [comment]
I have to find out also

**Comment by seertenedos** [comment]
Hey good news i found a project that works it seems. This project https://github.com/bishaldahal/Terabox-DL/tree/main has a link on the side to a hosted version of it at https://terabox-dl.qtcloud.workers.dev/ and when i tested it with a shared folder link it listed all the files and allowed download! I still need to workout how it is able to do it and hopefully duplicate otherwise i will have to bounce via the hosted site

**Comment by r0ld3x** [comment]
> Hey good news i found a project that works it seems. This project https://github.com/bishaldahal/Terabox-DL/tree/main has a link on the side to a hosted version of it at https://terabox-dl.qtcloud.workers.dev/ and when i tested it with a shared folder link it listed all the files and allowed download! I still need to workout how it is able to do it and hopefully duplicate otherwise i will have to bounce via the hosted site

I am not free these days but I'll make it possible as soon as I can
