### ISSUE TITLE
#Missing Cookie in env

### ISSUE THREAD

**Issue by Maher-Zubair** [r0ld3x/terabox-app#15]
Error: Missing COOKIE in env
--
11:30:52.398 | at 5051 (/vercel/path0/.next/server/app/api/route.js:147:11)
11:30:52.398 | at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:42)
11:30:52.398 | at __webpack_exec__ (/vercel/path0/.next/server/app/api/route.js:309:39)
11:30:52.398 | at /vercel/path0/.next/server/app/api/route.js:310:74
11:30:52.398 | at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:138:21)
11:30:52.398 | at /vercel/path0/.next/server/app/api/route.js:310:47
11:30:52.398 | at Object.<anonymous> (/vercel/path0/.next/server/app/api/route.js:313:3)
11:30:52.399 | at Module._compile (node:internal/modules/cjs/loader:1256:14)
11:30:52.399 | at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
11:30:52.399 | at Module.load (node:internal/modules/cjs/loader:1119:32)
11:30:52.457 |  
11:30:52.458 | > Build error occurred
11:30:52.458 | Error: Failed to collect page data for /api
11:30:52.460 | at /vercel/path0/node_modules/next/dist/build/utils.js:1156:15
11:30:52.463 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
11:30:52.463 | type: 'Error'
11:30:52.463 | }
11:30:52.486 | Error: Command "npm run build" exited with 1

**Comment by r0ld3x** [comment]
You have to use premium acount not free one

**Comment by Maher-Zubair** [comment]
_are you talking about vercel account_

**Comment by r0ld3x** [comment]
> _are you talking about vercel account_

Cookie

**Comment by Maher-Zubair** [comment]
_but how man, from where i get cookie i just try to host from repo but stills same then how your working_

**Comment by r0ld3x** [comment]
> _but how man, from where i get cookie i just try to host from repo but stills same then how your working_

check README.md

**Comment by Maher-Zubair** [comment]
_yeah i did and i got it thanks_
_but the issue is how to get premium account for free_

**Comment by r0ld3x** [comment]
> _yeah i did and i got it thanks_
> _but the issue is how to get premium account for free_

No you can't
