### ISSUE TITLE
"Unknown Error"

### ISSUE THREAD

**Issue by bolbolfolfol** [r0ld3x/terabox-app#3]
Thank you for the website
but most of my downloads are protected with passwords
Can you add a password compatibility please
Thx !

**Comment by r0ld3x** [comment]
I am working upon it  :) 

Thanks for this issue

also can you provide me a terabox protected lnk with password :)

**Comment by bolbolfolfol** [comment]
> I am working upon it :)
> 
> Thanks for this issue
> 
> also can you provide me a terabox protected lnk with password :)

This
https://terabox.com/s/1UaQWa3vg4b8Y1Yg4vel4WA
pass : 5dgd
