### ISSUE TITLE
IN which file, setup environment.

### ISSUE THREAD

**Issue by sahilkundu** [r0ld3x/terabox-app#6]
NEXT_PUBLIC_SECRET_KEY=yoursecretkey

**Comment by r0ld3x** [comment]
> NEXT_PUBLIC_SECRET_KEY=yoursecretkey
> 
> 

.env

**Comment by r0ld3x** [comment]
> NEXT_PUBLIC_SECRET_KEY=yoursecretkey
> 
> 

.env @sahilkundu
